const BASE_URL = 'https://api.thecatapi.com/v1/';

const catsListMock = [
  {
    breeds: [
      {
        weight: { imperial: '6 - 12', metric: '3 - 5' },
        id: 'bure',
        name: 'Burmese',
        cfa_url: 'http://cfa.org/Breeds/BreedsAB/Burmese.aspx',
        vetstreet_url: 'http://www.vetstreet.com/cats/burmese',
        vcahospitals_url:
          'https://vcahospitals.com/know-your-pet/cat-breeds/burmese',
        temperament:
          'Curious, Intelligent, Gentle, Social, Interactive, Playful, Lively',
        origin: 'Burma',
        country_codes: 'MM',
        country_code: 'MM',
        description:
          'Burmese love being with people, playing with them, and keeping them entertained. They crave close physical contact and abhor an empty lap. They will follow their humans from room to room, and sleep in bed with them, preferably under the covers, cuddled as close as possible. At play, they will turn around to see if their human is watching and being entertained by their crazy antics.',
        life_span: '15 - 16',
        indoor: 0,
        lap: 1,
        alt_names: '',
        adaptability: 5,
        affection_level: 5,
        child_friendly: 4,
        dog_friendly: 5,
        energy_level: 4,
        grooming: 1,
        health_issues: 3,
        intelligence: 5,
        shedding_level: 3,
        social_needs: 5,
        stranger_friendly: 5,
        vocalisation: 5,
        experimental: 0,
        hairless: 0,
        natural: 0,
        rare: 0,
        rex: 0,
        suppressed_tail: 0,
        short_legs: 0,
        wikipedia_url: 'https://en.wikipedia.org/wiki/Burmese_(cat)',
        hypoallergenic: 1,
        reference_image_id: '4lXnnfxac',
      },
    ],
    id: '92D9NZLs0',
    url: 'https://cdn2.thecatapi.com/images/92D9NZLs0.jpg',
    width: 3260,
    height: 1685,
  },
  {
    breeds: [
      {
        weight: { imperial: '6 - 13', metric: '3 - 6' },
        id: 'buri',
        name: 'Burmilla',
        cfa_url: 'http://cfa.org/Breeds/BreedsAB/Burmilla.aspx',
        vetstreet_url: 'http://www.vetstreet.com/cats/burmilla',
        temperament:
          'Easy Going, Friendly, Intelligent, Lively, Playful, Social',
        origin: 'United Kingdom',
        country_codes: 'GB',
        country_code: 'GB',
        description:
          'The Burmilla is a fairly placid cat. She tends to be an easy cat to get along with, requiring minimal care. The Burmilla is affectionate and sweet and makes a good companion, the Burmilla is an ideal companion to while away a lonely evening. Loyal, devoted, and affectionate, this cat will stay by its owner, always keeping them company.',
        life_span: '10 - 15',
        indoor: 0,
        lap: 1,
        alt_names: '',
        adaptability: 5,
        affection_level: 5,
        child_friendly: 4,
        dog_friendly: 4,
        energy_level: 3,
        grooming: 3,
        health_issues: 3,
        intelligence: 3,
        shedding_level: 3,
        social_needs: 4,
        stranger_friendly: 3,
        vocalisation: 5,
        experimental: 0,
        hairless: 0,
        natural: 0,
        rare: 0,
        rex: 0,
        suppressed_tail: 0,
        short_legs: 0,
        wikipedia_url: 'https://en.wikipedia.org/wiki/Burmilla',
        hypoallergenic: 0,
        reference_image_id: 'jvg3XfEdC',
      },
    ],
    id: 'J4Jv10E7O',
    url: 'https://cdn2.thecatapi.com/images/J4Jv10E7O.jpg',
    width: 4608,
    height: 3072,
  },
  {
    breeds: [
      {
        weight: { imperial: '5 - 10', metric: '2 - 5' },
        id: 'drex',
        name: 'Devon Rex',
        cfa_url: 'http://cfa.org/Breeds/BreedsCJ/DevonRex.aspx',
        vetstreet_url: 'http://www.vetstreet.com/cats/devon-rex',
        vcahospitals_url:
          'https://vcahospitals.com/know-your-pet/cat-breeds/devon-rex',
        temperament: 'Highly interactive, Mischievous, Loyal, Social, Playful',
        origin: 'United Kingdom',
        country_codes: 'GB',
        country_code: 'GB',
        description:
          'The favourite perch of the Devon Rex is right at head level, on the shoulder of her favorite person. She takes a lively interest in everything that is going on and refuses to be left out of any activity. Count on her to stay as close to you as possible, occasionally communicating his opinions in a quiet voice. She loves people and welcomes the attentions of friends and family alike.',
        life_span: '10 - 15',
        indoor: 0,
        lap: 1,
        alt_names: 'Pixie cat, Alien cat, Poodle cat',
        adaptability: 5,
        affection_level: 5,
        child_friendly: 4,
        dog_friendly: 5,
        energy_level: 5,
        grooming: 1,
        health_issues: 3,
        intelligence: 5,
        shedding_level: 1,
        social_needs: 5,
        stranger_friendly: 5,
        vocalisation: 1,
        experimental: 0,
        hairless: 0,
        natural: 0,
        rare: 0,
        rex: 1,
        suppressed_tail: 0,
        short_legs: 0,
        wikipedia_url: 'https://en.wikipedia.org/wiki/Devon_Rex',
        hypoallergenic: 1,
        reference_image_id: '4RzEwvyzz',
      },
    ],
    id: 'jnqO9lwG2',
    url: 'https://cdn2.thecatapi.com/images/jnqO9lwG2.jpg',
    width: 845,
    height: 583,
  },
  {
    breeds: [
      {
        weight: { imperial: '5 - 10', metric: '2 - 5' },
        id: 'drex',
        name: 'Devon Rex',
        cfa_url: 'http://cfa.org/Breeds/BreedsCJ/DevonRex.aspx',
        vetstreet_url: 'http://www.vetstreet.com/cats/devon-rex',
        vcahospitals_url:
          'https://vcahospitals.com/know-your-pet/cat-breeds/devon-rex',
        temperament: 'Highly interactive, Mischievous, Loyal, Social, Playful',
        origin: 'United Kingdom',
        country_codes: 'GB',
        country_code: 'GB',
        description:
          'The favourite perch of the Devon Rex is right at head level, on the shoulder of her favorite person. She takes a lively interest in everything that is going on and refuses to be left out of any activity. Count on her to stay as close to you as possible, occasionally communicating his opinions in a quiet voice. She loves people and welcomes the attentions of friends and family alike.',
        life_span: '10 - 15',
        indoor: 0,
        lap: 1,
        alt_names: 'Pixie cat, Alien cat, Poodle cat',
        adaptability: 5,
        affection_level: 5,
        child_friendly: 4,
        dog_friendly: 5,
        energy_level: 5,
        grooming: 1,
        health_issues: 3,
        intelligence: 5,
        shedding_level: 1,
        social_needs: 5,
        stranger_friendly: 5,
        vocalisation: 1,
        experimental: 0,
        hairless: 0,
        natural: 0,
        rare: 0,
        rex: 1,
        suppressed_tail: 0,
        short_legs: 0,
        wikipedia_url: 'https://en.wikipedia.org/wiki/Devon_Rex',
        hypoallergenic: 1,
        reference_image_id: '4RzEwvyzz',
      },
    ],
    id: '4RzEwvyzz',
    url: 'https://cdn2.thecatapi.com/images/4RzEwvyzz.png',
    width: 1729,
    height: 1160,
  },
  {
    breeds: [
      {
        weight: { imperial: '7 - 14', metric: '3 - 6' },
        id: 'esho',
        name: 'Exotic Shorthair',
        cfa_url: 'http://cfa.org/Breeds/BreedsCJ/Exotic.aspx',
        vetstreet_url: 'http://www.vetstreet.com/cats/exotic-shorthair',
        vcahospitals_url:
          'https://vcahospitals.com/know-your-pet/cat-breeds/exotic-shorthair',
        temperament: 'Affectionate, Sweet, Loyal, Quiet, Peaceful',
        origin: 'United States',
        country_codes: 'US',
        country_code: 'US',
        description:
          'The Exotic Shorthair is a gentle friendly cat that has the same personality as the Persian. They love having fun, don’t mind the company of other cats and dogs, also love to curl up for a sleep in a safe place. Exotics love their own people, but around strangers they are cautious at first. Given time, they usually warm up to visitors.',
        life_span: '12 - 15',
        indoor: 0,
        lap: 1,
        alt_names: 'Exotic',
        adaptability: 5,
        affection_level: 5,
        child_friendly: 3,
        dog_friendly: 3,
        energy_level: 3,
        grooming: 2,
        health_issues: 3,
        intelligence: 3,
        shedding_level: 2,
        social_needs: 4,
        stranger_friendly: 2,
        vocalisation: 1,
        experimental: 0,
        hairless: 0,
        natural: 0,
        rare: 0,
        rex: 0,
        suppressed_tail: 0,
        short_legs: 0,
        wikipedia_url: 'https://en.wikipedia.org/wiki/Exotic_Shorthair',
        hypoallergenic: 0,
        reference_image_id: 'YnPrYEmfe',
      },
    ],
    id: 'YnPrYEmfe',
    url: 'https://cdn2.thecatapi.com/images/YnPrYEmfe.jpg',
    width: 1024,
    height: 768,
  },
  {
    breeds: [
      {
        weight: { imperial: '7 - 14', metric: '3 - 6' },
        id: 'esho',
        name: 'Exotic Shorthair',
        cfa_url: 'http://cfa.org/Breeds/BreedsCJ/Exotic.aspx',
        vetstreet_url: 'http://www.vetstreet.com/cats/exotic-shorthair',
        vcahospitals_url:
          'https://vcahospitals.com/know-your-pet/cat-breeds/exotic-shorthair',
        temperament: 'Affectionate, Sweet, Loyal, Quiet, Peaceful',
        origin: 'United States',
        country_codes: 'US',
        country_code: 'US',
        description:
          'The Exotic Shorthair is a gentle friendly cat that has the same personality as the Persian. They love having fun, don’t mind the company of other cats and dogs, also love to curl up for a sleep in a safe place. Exotics love their own people, but around strangers they are cautious at first. Given time, they usually warm up to visitors.',
        life_span: '12 - 15',
        indoor: 0,
        lap: 1,
        alt_names: 'Exotic',
        adaptability: 5,
        affection_level: 5,
        child_friendly: 3,
        dog_friendly: 3,
        energy_level: 3,
        grooming: 2,
        health_issues: 3,
        intelligence: 3,
        shedding_level: 2,
        social_needs: 4,
        stranger_friendly: 2,
        vocalisation: 1,
        experimental: 0,
        hairless: 0,
        natural: 0,
        rare: 0,
        rex: 0,
        suppressed_tail: 0,
        short_legs: 0,
        wikipedia_url: 'https://en.wikipedia.org/wiki/Exotic_Shorthair',
        hypoallergenic: 0,
        reference_image_id: 'YnPrYEmfe',
      },
    ],
    id: 'FCNqMC83P',
    url: 'https://cdn2.thecatapi.com/images/FCNqMC83P.jpg',
    width: 1083,
    height: 971,
  },
  {
    breeds: [
      {
        weight: { imperial: '7 - 14', metric: '3 - 6' },
        id: 'esho',
        name: 'Exotic Shorthair',
        cfa_url: 'http://cfa.org/Breeds/BreedsCJ/Exotic.aspx',
        vetstreet_url: 'http://www.vetstreet.com/cats/exotic-shorthair',
        vcahospitals_url:
          'https://vcahospitals.com/know-your-pet/cat-breeds/exotic-shorthair',
        temperament: 'Affectionate, Sweet, Loyal, Quiet, Peaceful',
        origin: 'United States',
        country_codes: 'US',
        country_code: 'US',
        description:
          'The Exotic Shorthair is a gentle friendly cat that has the same personality as the Persian. They love having fun, don’t mind the company of other cats and dogs, also love to curl up for a sleep in a safe place. Exotics love their own people, but around strangers they are cautious at first. Given time, they usually warm up to visitors.',
        life_span: '12 - 15',
        indoor: 0,
        lap: 1,
        alt_names: 'Exotic',
        adaptability: 5,
        affection_level: 5,
        child_friendly: 3,
        dog_friendly: 3,
        energy_level: 3,
        grooming: 2,
        health_issues: 3,
        intelligence: 3,
        shedding_level: 2,
        social_needs: 4,
        stranger_friendly: 2,
        vocalisation: 1,
        experimental: 0,
        hairless: 0,
        natural: 0,
        rare: 0,
        rex: 0,
        suppressed_tail: 0,
        short_legs: 0,
        wikipedia_url: 'https://en.wikipedia.org/wiki/Exotic_Shorthair',
        hypoallergenic: 0,
        reference_image_id: 'YnPrYEmfe',
      },
    ],
    id: 'HT902S6ra',
    url: 'https://cdn2.thecatapi.com/images/HT902S6ra.jpg',
    width: 1600,
    height: 1200,
  },
  {
    breeds: [
      {
        weight: { imperial: '7 - 11', metric: '3 - 5' },
        id: 'kora',
        name: 'Korat',
        cfa_url: 'http://cfa.org/Breeds/BreedsKthruR/Korat.aspx',
        vetstreet_url: 'http://www.vetstreet.com/cats/korat',
        vcahospitals_url:
          'https://vcahospitals.com/know-your-pet/cat-breeds/korat',
        temperament: 'Active, Loyal, highly intelligent, Expressive, Trainable',
        origin: 'Thailand',
        country_codes: 'TH',
        country_code: 'TH',
        description:
          'The Korat is a natural breed, and one of the oldest stable cat breeds. They are highly intelligent and confident cats that can be fearless, although they are startled by loud sounds and sudden movements. Korats form strong bonds with their people and like to cuddle and stay nearby.',
        life_span: '10 - 15',
        indoor: 0,
        adaptability: 5,
        affection_level: 5,
        child_friendly: 4,
        dog_friendly: 5,
        energy_level: 3,
        grooming: 1,
        health_issues: 1,
        intelligence: 5,
        shedding_level: 3,
        social_needs: 5,
        stranger_friendly: 2,
        vocalisation: 3,
        experimental: 0,
        hairless: 0,
        natural: 0,
        rare: 1,
        rex: 0,
        suppressed_tail: 0,
        short_legs: 0,
        wikipedia_url: 'https://en.wikipedia.org/wiki/Korat',
        hypoallergenic: 0,
        reference_image_id: 'DbwiefiaY',
      },
    ],
    id: 'DbwiefiaY',
    url: 'https://cdn2.thecatapi.com/images/DbwiefiaY.png',
    width: 1200,
    height: 627,
  },
  {
    breeds: [
      {
        weight: { imperial: '7 - 13', metric: '3 - 6' },
        id: 'manx',
        name: 'Manx',
        cfa_url: 'http://cfa.org/Breeds/BreedsKthruR/Manx.aspx',
        vetstreet_url: 'http://www.vetstreet.com/cats/manx',
        vcahospitals_url:
          'https://vcahospitals.com/know-your-pet/cat-breeds/manx',
        temperament: 'Easy Going, Intelligent, Loyal, Playful, Social',
        origin: 'Isle of Man',
        country_codes: 'IM',
        country_code: 'IM',
        description:
          'The Manx is a placid, sweet cat that is gentle and playful. She never seems to get too upset about anything. She is a loving companion and adores being with people.',
        life_span: '12 - 14',
        indoor: 0,
        lap: 1,
        alt_names: 'Manks, Stubbin, Rumpy',
        adaptability: 5,
        affection_level: 5,
        child_friendly: 4,
        dog_friendly: 5,
        energy_level: 5,
        grooming: 1,
        health_issues: 3,
        intelligence: 5,
        shedding_level: 5,
        social_needs: 5,
        stranger_friendly: 3,
        vocalisation: 3,
        experimental: 0,
        hairless: 0,
        natural: 1,
        rare: 0,
        rex: 0,
        suppressed_tail: 1,
        short_legs: 0,
        wikipedia_url: 'https://en.wikipedia.org/wiki/Manx_(cat)',
        hypoallergenic: 0,
        reference_image_id: 'fhYh2PDcC',
      },
    ],
    id: 'Rscv6E1c5',
    url: 'https://cdn2.thecatapi.com/images/Rscv6E1c5.jpg',
    width: 1200,
    height: 900,
  },
  {
    breeds: [
      {
        weight: { imperial: '7 - 13', metric: '3 - 6' },
        id: 'manx',
        name: 'Manx',
        cfa_url: 'http://cfa.org/Breeds/BreedsKthruR/Manx.aspx',
        vetstreet_url: 'http://www.vetstreet.com/cats/manx',
        vcahospitals_url:
          'https://vcahospitals.com/know-your-pet/cat-breeds/manx',
        temperament: 'Easy Going, Intelligent, Loyal, Playful, Social',
        origin: 'Isle of Man',
        country_codes: 'IM',
        country_code: 'IM',
        description:
          'The Manx is a placid, sweet cat that is gentle and playful. She never seems to get too upset about anything. She is a loving companion and adores being with people.',
        life_span: '12 - 14',
        indoor: 0,
        lap: 1,
        alt_names: 'Manks, Stubbin, Rumpy',
        adaptability: 5,
        affection_level: 5,
        child_friendly: 4,
        dog_friendly: 5,
        energy_level: 5,
        grooming: 1,
        health_issues: 3,
        intelligence: 5,
        shedding_level: 5,
        social_needs: 5,
        stranger_friendly: 3,
        vocalisation: 3,
        experimental: 0,
        hairless: 0,
        natural: 1,
        rare: 0,
        rex: 0,
        suppressed_tail: 1,
        short_legs: 0,
        wikipedia_url: 'https://en.wikipedia.org/wiki/Manx_(cat)',
        hypoallergenic: 0,
        reference_image_id: 'fhYh2PDcC',
      },
    ],
    id: 'OXMyfVPcP',
    url: 'https://cdn2.thecatapi.com/images/OXMyfVPcP.jpg',
    width: 1600,
    height: 1511,
  },
  {
    breeds: [
      {
        weight: { imperial: '7 - 15', metric: '3 - 7' },
        id: 'ocic',
        name: 'Ocicat',
        cfa_url: 'http://cfa.org/Breeds/BreedsKthruR/Ocicat.aspx',
        vetstreet_url: 'http://www.vetstreet.com/cats/ocicat',
        vcahospitals_url:
          'https://vcahospitals.com/know-your-pet/cat-breeds/ocicat',
        temperament:
          'Active, Agile, Curious, Demanding, Friendly, Gentle, Lively, Playful, Social',
        origin: 'United States',
        country_codes: 'US',
        country_code: 'US',
        description:
          "Loyal and devoted to their owners, the Ocicat is intelligent, confident, outgoing, and seems to have many dog traits. They can be trained to fetch toys, walk on a lead, taught to 'speak', come when called, and follow other commands. ",
        life_span: '12 - 14',
        indoor: 0,
        alt_names: '',
        adaptability: 5,
        affection_level: 5,
        child_friendly: 4,
        dog_friendly: 5,
        energy_level: 5,
        grooming: 1,
        health_issues: 3,
        intelligence: 5,
        shedding_level: 3,
        social_needs: 5,
        stranger_friendly: 5,
        vocalisation: 3,
        experimental: 0,
        hairless: 0,
        natural: 0,
        rare: 0,
        rex: 0,
        suppressed_tail: 0,
        short_legs: 0,
        wikipedia_url: 'https://en.wikipedia.org/wiki/Ocicat',
        hypoallergenic: 1,
        reference_image_id: 'JAx-08Y0n',
      },
    ],
    id: 'imz2EwFWv',
    url: 'https://cdn2.thecatapi.com/images/imz2EwFWv.jpg',
    width: 1280,
    height: 850,
  },
  {
    breeds: [
      {
        weight: { imperial: '5 - 10', metric: '2 - 5' },
        id: 'orie',
        name: 'Oriental',
        cfa_url: 'http://cfa.org/Breeds/BreedsKthruR/Oriental.aspx',
        vetstreet_url: 'http://www.vetstreet.com/cats/oriental',
        vcahospitals_url:
          'https://vcahospitals.com/know-your-pet/cat-breeds/oriental',
        temperament:
          'Energetic, Affectionate, Intelligent, Social, Playful, Curious',
        origin: 'United States',
        country_codes: 'US',
        country_code: 'US',
        description:
          'Orientals are passionate about the people in their lives. They become extremely attached to their humans, so be prepared for a lifetime commitment. When you are not available to entertain her, an Oriental will divert herself by jumping on top of the refrigerator, opening drawers, seeking out new hideaways.',
        life_span: '12 - 14',
        indoor: 0,
        lap: 1,
        alt_names: 'Foreign Type',
        adaptability: 5,
        affection_level: 5,
        child_friendly: 4,
        dog_friendly: 5,
        energy_level: 5,
        grooming: 1,
        health_issues: 3,
        intelligence: 5,
        shedding_level: 3,
        social_needs: 5,
        stranger_friendly: 3,
        vocalisation: 5,
        experimental: 0,
        hairless: 0,
        natural: 0,
        rare: 0,
        rex: 0,
        suppressed_tail: 0,
        short_legs: 0,
        wikipedia_url: 'https://en.wikipedia.org/wiki/Oriental_Shorthair',
        hypoallergenic: 1,
        reference_image_id: 'LutjkZJpH',
      },
    ],
    id: 'Mt-cUeiUY',
    url: 'https://cdn2.thecatapi.com/images/Mt-cUeiUY.jpg',
    width: 1654,
    height: 2302,
  },
  {
    breeds: [
      {
        weight: { imperial: '5 - 10', metric: '2 - 5' },
        id: 'orie',
        name: 'Oriental',
        cfa_url: 'http://cfa.org/Breeds/BreedsKthruR/Oriental.aspx',
        vetstreet_url: 'http://www.vetstreet.com/cats/oriental',
        vcahospitals_url:
          'https://vcahospitals.com/know-your-pet/cat-breeds/oriental',
        temperament:
          'Energetic, Affectionate, Intelligent, Social, Playful, Curious',
        origin: 'United States',
        country_codes: 'US',
        country_code: 'US',
        description:
          'Orientals are passionate about the people in their lives. They become extremely attached to their humans, so be prepared for a lifetime commitment. When you are not available to entertain her, an Oriental will divert herself by jumping on top of the refrigerator, opening drawers, seeking out new hideaways.',
        life_span: '12 - 14',
        indoor: 0,
        lap: 1,
        alt_names: 'Foreign Type',
        adaptability: 5,
        affection_level: 5,
        child_friendly: 4,
        dog_friendly: 5,
        energy_level: 5,
        grooming: 1,
        health_issues: 3,
        intelligence: 5,
        shedding_level: 3,
        social_needs: 5,
        stranger_friendly: 3,
        vocalisation: 5,
        experimental: 0,
        hairless: 0,
        natural: 0,
        rare: 0,
        rex: 0,
        suppressed_tail: 0,
        short_legs: 0,
        wikipedia_url: 'https://en.wikipedia.org/wiki/Oriental_Shorthair',
        hypoallergenic: 1,
        reference_image_id: 'LutjkZJpH',
      },
    ],
    id: '6y4uxeRjW',
    url: 'https://cdn2.thecatapi.com/images/6y4uxeRjW.jpg',
    width: 3264,
    height: 2448,
  },
  {
    breeds: [
      {
        weight: { imperial: '5 - 11', metric: '2 - 5' },
        id: 'sfol',
        name: 'Scottish Fold',
        cfa_url: 'http://cfa.org/Breeds/BreedsSthruT/ScottishFold.aspx',
        vetstreet_url:
          'http://www.vetstreet.com/cats/scottish-fold-highland-fold',
        vcahospitals_url:
          'https://vcahospitals.com/know-your-pet/cat-breeds/scottish-fold',
        temperament:
          'Affectionate, Intelligent, Loyal, Playful, Social, Sweet, Loving',
        origin: 'United Kingdom',
        country_codes: 'GB',
        country_code: 'GB',
        description:
          'The Scottish Fold is a sweet, charming breed. She is an easy cat to live with and to care for. She is affectionate and is comfortable with all members of her family. Her tail should be handled gently. Folds are known for sleeping on their backs, and for sitting with their legs stretched out and their paws on their belly. This is called the "Buddha Position".',
        life_span: '11 - 14',
        indoor: 0,
        alt_names: 'Scot Fold',
        adaptability: 5,
        affection_level: 5,
        child_friendly: 4,
        dog_friendly: 5,
        energy_level: 3,
        grooming: 1,
        health_issues: 4,
        intelligence: 3,
        shedding_level: 3,
        social_needs: 3,
        stranger_friendly: 3,
        vocalisation: 1,
        experimental: 0,
        hairless: 0,
        natural: 0,
        rare: 0,
        rex: 0,
        suppressed_tail: 0,
        short_legs: 0,
        wikipedia_url: 'https://en.wikipedia.org/wiki/Scottish_Fold',
        hypoallergenic: 0,
        reference_image_id: 'o9t0LDcsa',
      },
    ],
    id: '83CUYAi3g',
    url: 'https://cdn2.thecatapi.com/images/83CUYAi3g.jpg',
    width: 1356,
    height: 668,
  },
  {
    breeds: [
      {
        weight: { imperial: '8 - 15', metric: '4 - 7' },
        id: 'siam',
        name: 'Siamese',
        cfa_url: 'http://cfa.org/Breeds/BreedsSthruT/Siamese.aspx',
        vetstreet_url: 'http://www.vetstreet.com/cats/siamese',
        vcahospitals_url:
          'https://vcahospitals.com/know-your-pet/cat-breeds/siamese',
        temperament: 'Active, Agile, Clever, Sociable, Loving, Energetic',
        origin: 'Thailand',
        country_codes: 'TH',
        country_code: 'TH',
        description:
          'While Siamese cats are extremely fond of their people, they will follow you around and supervise your every move, being talkative and opinionated. They are a demanding and social cat, that do not like being left alone for long periods.',
        life_span: '12 - 15',
        indoor: 0,
        lap: 1,
        alt_names: 'Siam, Thai Cat',
        adaptability: 5,
        affection_level: 5,
        child_friendly: 4,
        dog_friendly: 5,
        energy_level: 5,
        grooming: 1,
        health_issues: 1,
        intelligence: 5,
        shedding_level: 2,
        social_needs: 5,
        stranger_friendly: 5,
        vocalisation: 5,
        experimental: 0,
        hairless: 0,
        natural: 0,
        rare: 0,
        rex: 0,
        suppressed_tail: 0,
        short_legs: 0,
        wikipedia_url: 'https://en.wikipedia.org/wiki/Siamese_(cat)',
        hypoallergenic: 1,
        reference_image_id: 'ai6Jps4sx',
      },
    ],
    id: 'Ttk_tdV4g',
    url: 'https://cdn2.thecatapi.com/images/Ttk_tdV4g.jpg',
    width: 1152,
    height: 768,
  },
  {
    breeds: [
      {
        weight: { imperial: '6 - 12', metric: '3 - 5' },
        id: 'soma',
        name: 'Somali',
        cfa_url: 'http://cfa.org/Breeds/BreedsSthruT/Somali.aspx',
        vetstreet_url: 'http://www.vetstreet.com/cats/somali',
        vcahospitals_url:
          'https://vcahospitals.com/know-your-pet/cat-breeds/somali',
        temperament:
          'Mischievous, Tenacious, Intelligent, Affectionate, Gentle, Interactive, Loyal',
        origin: 'Somalia',
        country_codes: 'SO',
        country_code: 'SO',
        description:
          'The Somali lives life to the fullest. He climbs higher, jumps farther, plays harder. Nothing escapes the notice of this highly intelligent and inquisitive cat. Somalis love the company of humans and other animals.',
        life_span: '12 - 16',
        indoor: 0,
        alt_names: 'Fox Cat, Long-Haired Abyssinian',
        adaptability: 5,
        affection_level: 5,
        child_friendly: 3,
        dog_friendly: 4,
        energy_level: 5,
        grooming: 3,
        health_issues: 2,
        intelligence: 5,
        shedding_level: 4,
        social_needs: 5,
        stranger_friendly: 5,
        vocalisation: 1,
        experimental: 0,
        hairless: 0,
        natural: 0,
        rare: 0,
        rex: 0,
        suppressed_tail: 0,
        short_legs: 0,
        wikipedia_url: 'https://en.wikipedia.org/wiki/Somali_(cat)',
        hypoallergenic: 0,
        reference_image_id: 'EPF2ejNS0',
      },
    ],
    id: 'K4WzCAYWm',
    url: 'https://cdn2.thecatapi.com/images/K4WzCAYWm.jpg',
    width: 811,
    height: 1217,
  },
  {
    breeds: [
      {
        weight: { imperial: '7 - 14', metric: '3 - 6' },
        id: 'ebur',
        name: 'European Burmese',
        cfa_url: 'http://cfa.org/Breeds/BreedsCJ/EuropeanBurmese.aspx',
        temperament: 'Sweet, Affectionate, Loyal',
        origin: 'Burma',
        country_codes: 'MM',
        country_code: 'MM',
        description:
          'The European Burmese is a very affectionate, intelligent, and loyal cat. They thrive on companionship and will want to be with you, participating in everything you do. While they might pick a favorite family member, chances are that they will interact with everyone in the home, as well as any visitors that come to call. They are inquisitive and playful, even as adults. ',
        life_span: '10 - 15',
        indoor: 0,
        lap: 1,
        alt_names: '',
        adaptability: 5,
        affection_level: 5,
        child_friendly: 4,
        cat_friendly: 4,
        dog_friendly: 4,
        energy_level: 4,
        grooming: 1,
        health_issues: 4,
        intelligence: 5,
        shedding_level: 3,
        social_needs: 5,
        stranger_friendly: 5,
        vocalisation: 4,
        experimental: 0,
        hairless: 0,
        natural: 0,
        rare: 0,
        rex: 0,
        suppressed_tail: 0,
        short_legs: 0,
        hypoallergenic: 0,
      },
    ],
    id: 'oLtx9gsxx',
    url: 'https://cdn2.thecatapi.com/images/oLtx9gsxx.jpg',
    width: 4027,
    height: 2680,
  },
  {
    breeds: [
      {
        weight: { imperial: '6 - 12', metric: '3 - 5' },
        id: 'soma',
        name: 'Somali',
        cfa_url: 'http://cfa.org/Breeds/BreedsSthruT/Somali.aspx',
        vetstreet_url: 'http://www.vetstreet.com/cats/somali',
        vcahospitals_url:
          'https://vcahospitals.com/know-your-pet/cat-breeds/somali',
        temperament:
          'Mischievous, Tenacious, Intelligent, Affectionate, Gentle, Interactive, Loyal',
        origin: 'Somalia',
        country_codes: 'SO',
        country_code: 'SO',
        description:
          'The Somali lives life to the fullest. He climbs higher, jumps farther, plays harder. Nothing escapes the notice of this highly intelligent and inquisitive cat. Somalis love the company of humans and other animals.',
        life_span: '12 - 16',
        indoor: 0,
        alt_names: 'Fox Cat, Long-Haired Abyssinian',
        adaptability: 5,
        affection_level: 5,
        child_friendly: 3,
        dog_friendly: 4,
        energy_level: 5,
        grooming: 3,
        health_issues: 2,
        intelligence: 5,
        shedding_level: 4,
        social_needs: 5,
        stranger_friendly: 5,
        vocalisation: 1,
        experimental: 0,
        hairless: 0,
        natural: 0,
        rare: 0,
        rex: 0,
        suppressed_tail: 0,
        short_legs: 0,
        wikipedia_url: 'https://en.wikipedia.org/wiki/Somali_(cat)',
        hypoallergenic: 0,
        reference_image_id: 'EPF2ejNS0',
      },
    ],
    id: 'pmhGxB9-m',
    url: 'https://cdn2.thecatapi.com/images/pmhGxB9-m.jpg',
    width: 1080,
    height: 1239,
  },
  {
    breeds: [
      {
        weight: { imperial: '6 - 12', metric: '3 - 5' },
        id: 'tonk',
        name: 'Tonkinese',
        cfa_url: 'http://cfa.org/Breeds/BreedsSthruT/Tonkinese.aspx',
        vetstreet_url: 'http://www.vetstreet.com/cats/tonkinese',
        vcahospitals_url:
          'https://vcahospitals.com/know-your-pet/cat-breeds/tonkinese',
        temperament:
          'Curious, Intelligent, Social, Lively, Outgoing, Playful, Affectionate',
        origin: 'Canada',
        country_codes: 'CA',
        country_code: 'CA',
        description:
          'Intelligent and generous with their affection, a Tonkinese will supervise all activities with curiosity. Loving, social, active, playful, yet content to be a lap cat',
        life_span: '14 - 16',
        indoor: 0,
        lap: 1,
        alt_names: 'Tonk',
        adaptability: 5,
        affection_level: 5,
        child_friendly: 4,
        dog_friendly: 5,
        energy_level: 5,
        grooming: 1,
        health_issues: 1,
        intelligence: 5,
        shedding_level: 3,
        social_needs: 5,
        stranger_friendly: 5,
        vocalisation: 5,
        experimental: 0,
        hairless: 0,
        natural: 0,
        rare: 0,
        rex: 0,
        suppressed_tail: 0,
        short_legs: 0,
        wikipedia_url: 'https://en.wikipedia.org/wiki/Tonkinese_(cat)',
        hypoallergenic: 0,
        reference_image_id: 'KBroiVNCM',
      },
    ],
    id: 'A7Dsj7g1x',
    url: 'https://cdn2.thecatapi.com/images/A7Dsj7g1x.png',
    width: 1332,
    height: 674,
  },
  {
    breeds: [
      {
        weight: { imperial: '7  -  10', metric: '3 - 5' },
        id: 'abys',
        name: 'Abyssinian',
        cfa_url: 'http://cfa.org/Breeds/BreedsAB/Abyssinian.aspx',
        vetstreet_url: 'http://www.vetstreet.com/cats/abyssinian',
        vcahospitals_url:
          'https://vcahospitals.com/know-your-pet/cat-breeds/abyssinian',
        temperament: 'Active, Energetic, Independent, Intelligent, Gentle',
        origin: 'Egypt',
        country_codes: 'EG',
        country_code: 'EG',
        description:
          'The Abyssinian is easy to care for, and a joy to have in your home. They’re affectionate cats and love both people and other animals.',
        life_span: '14 - 15',
        indoor: 0,
        lap: 1,
        alt_names: '',
        adaptability: 5,
        affection_level: 5,
        child_friendly: 3,
        dog_friendly: 4,
        energy_level: 5,
        grooming: 1,
        health_issues: 2,
        intelligence: 5,
        shedding_level: 2,
        social_needs: 5,
        stranger_friendly: 5,
        vocalisation: 1,
        experimental: 0,
        hairless: 0,
        natural: 1,
        rare: 0,
        rex: 0,
        suppressed_tail: 0,
        short_legs: 0,
        wikipedia_url: 'https://en.wikipedia.org/wiki/Abyssinian_(cat)',
        hypoallergenic: 0,
        reference_image_id: '0XYvRd7oD',
      },
    ],
    id: 'rRLX_RH_o',
    url: 'https://cdn2.thecatapi.com/images/rRLX_RH_o.jpg',
    width: 299,
    height: 168,
  },
];

const filterBreeds = (cats) => {
  if (!cats) {
    return;
  }

  const breeds = {};

  return cats.filter((item) => {
    if (breeds[item.breeds[0].id]) {
      return;
    }
    breeds[item.breeds[0].id] = 1;
    return item;
  });
};

const getCats = async () => {
  // const data = await fetch(`${BASE_URL}images/search?limit=20&has_breeds=1`, {
  //   headers: {
  //     'x-api-key':
  //       'live_D5fHsYnbm5OuVsCXU5gMkN5fhbCBjOiTza3dvD6bhBwcMhSH6WvzrnMivvawMET6',
  //   },
  // });
  // const cats = await data.json();
  return new Promise((res, rej) => {
    res(filterBreeds(catsListMock));
  });
  return filterBreeds(cats);
};

export { getCats, catsListMock };
